name: Auto Commit

on:
  schedule:
  - cron: "*/30 * * * *"  # Runs every 30 minutes
  push:
    branches:
      - main

jobs:
  update-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.name "SAFAL-TIWARI"
          git config --local user.email "safaltiwari602@gmail.com"

      - name: Make Changes and Commit
        run: |
          echo "Automated commit at $(date)" >> activity.log
          git add activity.log
          git commit -m "Automated commit at $(date)" || exit 0

      - name: Push Changes
        run: |
          git push
